version : "3.5"

services : 
  nginx :
    build : ./requirement/nginx
    container_name : nginx
    restart : always
    env_file :
      - .env
    ports:
      - "443:443"
    depends_on :
      - wordpress
    volumes :
      - wp:/var/www/html 
    networks :
      - inception-network

  wordpress :
    build : ./requirement/wordpress
    container_name : wordpress
    depends_on :
      - mariadb
    restart : always
    env_file :
      - .env
    ports:
      - "9000:9000"
    volumes :
      - wp:/var/www/html
    networks :
      - inception-network

  mariadb :
    build : ./requirement/mariadb
    container_name : mariadb
    restart : always
    env_file :
      - .env
    ports:
      - "3306:3306"
    volumes :
      - db:/var/lib/mysql
    networks :
      - inception-network

volumes:
    wp:
      driver: local
      name: wp
      driver_opts:
        type: none
        o: bind
        device: /home/kle-guen/data/wordpress
    db:
      driver: local
      name: db
      driver_opts:
        type: none
        o: bind
        device: /home/kle-guen/data/mariadb

networks : 
  inception-network :
    name : inception-network
    driver : bridge
